[package]
name = "cargo-diagram"
version = "0.1.1"
edition = "2021"
authors = ["Etienne Schmidt <eschmidt@schmidt-ti.eu>"]
description = "Creates diagrams about your crate"
license = "MIT"
repository = "https://github.com/gladion136/cargo-diagram"

[dependencies]
cargo-diagram-visitors = "0.1.1"
cargo-diagram-printers = "0.1.1"
tracing = "0"
